### ISSUE TITLE
--enable parameter: rule is analyzed twice

### ISSUE THREAD

**Issue by jmini** [selesse/jxlint#17]
I have run `jxlint-impl` (version `2.0.0-SNAPSHOT`) with these arguments:
```
--html report.html 
--enable "Functions starting with 'test' are tests" 
example-project-java/src
```

The output report shows that the rule `FunctionsStartingWithTestAreTests` is used twice.

![jxlint report example](https://user-images.githubusercontent.com/1222165/27705772-3b9d5f22-5d0f-11e7-8046-c5fef1f2cf97.png)

I my opinion the `Dispatcher` should check for duplicates (using an `HashMap` for example).

---
In addition to this duplicate issue, I also have some concurrency error with the version `2.0.0-SNAPSHOT`:

```
java.util.ConcurrentModificationException: null
	at java.util.ArrayList.sort(ArrayList.java:1456) ~[na:1.8.0_102]
	at java.util.Collections.sort(Collections.java:175) ~[na:1.8.0_102]
	at com.selesse.jxlint.linter.ValidationThread.call(ValidationThread.java:31) ~[jxlint-2.0.0-SNAPSHOT.jar:na]
	at com.selesse.jxlint.linter.ValidationThread.call(ValidationThread.java:16) ~[jxlint-2.0.0-SNAPSHOT.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) ~[guava-19.0.jar:na]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
```

This might be an unrelated Issue (I hope I will find time to investigate).

**Comment by jmini** [comment]
I am working on a patch for this one (work in progress, I want to have unit tests)
