### ISSUE TITLE
CLI Tool: ClassNotFoundException: javax.servlet.HttpConstraintElement

### ISSUE THREAD

**Issue by jmini** [selesse/jxlint#29]
I am running a CLI Tool based on `jxlint-cli` (version `2.0.0-SNAPSHOT`):

```
java -cp lib/* my.Main --web
```

And I got this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/HttpConstraintElement
        at com.selesse.jxlint.actions.web.JettyWebRunner.startJetty(JettyWebRunner.java:61)
        at com.selesse.jxlint.actions.web.JettyWebRunner.startJettyHeadless(JettyWebRunner.java:35)
        at com.selesse.jxlint.actions.web.JettyWebRunner.start(JettyWebRunner.java:30)
        at com.selesse.jxlint.Dispatcher.startWebServer(Dispatcher.java:42)
        at com.selesse.jxlint.model.AbstractDispatcher.doDispatch(AbstractDispatcher.java:69)
        at com.selesse.jxlint.Dispatcher.dispatch(Dispatcher.java:25)
        at com.selesse.jxlint.Jxlint.parseArgumentsAndDispatch(Jxlint.java:95)
        at my.Main.main(Main.java:15)
Caused by: java.lang.ClassNotFoundException: javax.servlet.HttpConstraintElement
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more
```

The `lib/` is built with the maven assembly plugin (extract of the maven assembly xml file):

```
    <!-- Adds the dependencies and our application to the lib directory -->
    <dependencySets>
        <dependencySet>
            <outputDirectory>lib</outputDirectory>
            <unpack>false</unpack>
        </dependencySet>
    </dependencySets>
```

And contains following jars:

* annotations-3.0.1.jar
* asm-5.0.3.jar
* asm-analysis-5.0.3.jar
* asm-tree-5.0.3.jar
* asm-util-5.0.3.jar
* bootstrap-3.1.0.jar
* com.sun.el-2.2.0.v201108011116.jar
* commons-cli-1.3.1.jar
* commons-collections-3.2.1.jar
* commons-lang-2.4.jar
* guava-19.0.jar
* jansi-1.14.jar
* javax.el-2.2.0.v201108011116.jar
* javax.servlet-2.5.0.v201103041518.jar
* javax.servlet.jsp-2.2.0.v201112011158.jar
* javax.servlet.jsp.jstl-1.2.0.v201105211821.jar
* jcip-annotations-1.0.jar
* jetty-continuation-8.1.15.v20140411.jar
* jetty-http-8.1.15.v20140411.jar
* jetty-io-8.1.15.v20140411.jar
* jetty-jsp-8.1.15.v20140411.jar
* jetty-security-8.1.15.v20140411.jar
* jetty-server-8.1.15.v20140411.jar
* jetty-servlet-8.1.15.v20140411.jar
* jetty-util-8.1.15.v20140411.jar
* jetty-webapp-8.1.15.v20140411.jar
* jetty-xml-8.1.15.v20140411.jar
* jquery-1.9.0.jar
* jsr305-3.0.1.jar
* jxlint-2.0.0-SNAPSHOT.jar
* jxlint-cli-2.0.0-SNAPSHOT.jar
* logback-classic-1.1.2.jar
* logback-core-1.1.2.jar
* org.apache.jasper.glassfish-2.2.2.v201112011158.jar
* org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar
* org.eclipse.jdt.core-3.7.1.jar
* parboiled-core-1.1.7.jar
* parboiled-java-1.1.7.jar
* pegdown-1.6.0.jar
* prettify-4-Mar-2013.jar
* slf4j-api-1.7.21.jar
* tablesorter-2.15.5.jar
* velocity-1.7.jar
* and the jars for my project

The problem comes from the `javax.servlet-2.5.0.v201103041518.jar` the correct version should be ` javax.servlet-3.0.0.v201112011016.jar` (this version contains the missing `javax.servlet.HttpConstraintElement` class)

This can of course be fixed at project level in the pom with:

```
<dependency>
  <groupId>org.eclipse.jetty.orbit</groupId>
  <artifactId>javax.servlet</artifactId>
  <version>3.0.0.v201112011016</version>
</dependency>
```

I am not sure if gradle does a better job with the dependencies resolution, but in my opinion the dependencies should be correct at framework level.

**Comment by jmini** [comment]
In my opinion, a good solution could be to update the jetty version to `9.2.22.v20170606`. With this version the maven assembly plugin puts this javax servlet jar in the `lib/` folder: `javax.servlet-api-3.1.0.jar`

My tests show that the cli tool with `--web` works well.

**Comment by jmini** [comment]
I have pushed an example using the maven-assembly plugin on the `test_v2.0.0` branch in my `jxlint-experiments` project.

See: https://github.com/jmini/jxlint-experiments/tree/test_v2.0.0 (in particular commit [0fd1d1f](https://github.com/jmini/jxlint-experiments/commit/0fd1d1ff79195f8da20e6abac064dcf483ee7983))
